### ISSUE TITLE
Add license?

### ISSUE THREAD

**Issue by bryan-lunt** [NickStrupat/CacheLineSize#3]
I want to use this code in one of my projects / assignments for students.
If you could explicitly license it (preferably with headers), then that would be possible.

Thanks!

**Comment by NickStrupat** [comment]
Hi Bryan! I didn't realize this project didn't have a license. I'd love to add one so you and your students can use it.

I've added the MIT license to the repo.

**Comment by bryan-lunt** [comment]
This is great! Thanks Nick!
